export const DEMO_SCENARIOS = {
  hot: {
    key: 'hot',
    label: 'Hot Lead',
    status: 'ready_for_call',
    priority: 'P1',
    segment: 'hot',
    badge: 'Rueckruf innerhalb von 15 Minuten',
    firstName: 'Helena',
    lastName: 'Kaufbereit',
    email: 'novahaus.demo.hot@example.com',
    phone: '+49 151 10000001',
    wohnung: '4-zimmer',
    wohnungLabel: '4-Zimmer mit Dachterrasse',
    zeitrahmen: 'sofort',
    zeitrahmenLabel: 'So schnell wie moeglich',
    eigenkapital: 'ueber-80k',
    eigenkapitalLabel: 'Ueber 80.000 EUR',
    finanzierung: 'vorhanden',
    finanzierungLabel: 'Finanzierungszusage vorhanden',
    score: 92,
    nextAction: 'Callcenter ruft innerhalb von 15 Minuten an und sendet Expose.',
    emailSubject: 'Ihr Expose und ein kurzer Abstimmungstermin',
    emailDraft:
      'Hallo Helena,\n\nvielen Dank fuer Ihr Interesse an der 4-Zimmer-Wohnung mit Dachterrasse. Ihre Angaben passen sehr gut zu einem kurzfristigen Beratungsgespraech.\n\nDarf unser Team Sie heute kurz telefonisch erreichen, um die naechsten Schritte und verfuegbare Besichtigungstermine abzustimmen?\n\nViele Gruesse\nNovaHaus Immobilien',
  },
  warm: {
    key: 'warm',
    label: 'Warm Lead',
    status: 'ai_follow_up',
    priority: 'P2',
    segment: 'warm',
    badge: 'AI fragt Finanzierung nach',
    firstName: 'Martin',
    lastName: 'Finanzierung',
    email: 'novahaus.demo.warm@example.com',
    phone: '+49 151 10000002',
    wohnung: '3-zimmer',
    wohnungLabel: '3-Zimmer mit Garten',
    zeitrahmen: '3-6-monate',
    zeitrahmenLabel: 'In den naechsten 3-6 Monaten',
    eigenkapital: '50-80k',
    eigenkapitalLabel: '50.000-80.000 EUR',
    finanzierung: 'in-planung',
    finanzierungLabel: 'Finanzierung in Planung',
    score: 78,
    nextAction: 'AI-Draft mit einer klaren Finanzierungsfrage vorbereiten.',
    emailSubject: 'Kurze Rueckfrage zu Ihrer Finanzierung',
    emailDraft:
      'Hallo Martin,\n\nvielen Dank fuer Ihre Anfrage zur 3-Zimmer-Wohnung mit Garten. Damit wir Ihnen direkt die passenden naechsten Schritte senden koennen: Haben Sie bereits mit einer Bank oder einem Finanzierungsberater ueber den Kauf gesprochen?\n\nWenn Sie moechten, koennen wir danach einen kurzen Telefontermin mit unserem Team koordinieren.\n\nViele Gruesse\nNovaHaus Immobilien',
  },
  cold: {
    key: 'cold',
    label: 'Cold Lead',
    status: 'nurture',
    priority: 'P3',
    segment: 'cold',
    badge: 'Nurture statt Sofort-Call',
    firstName: 'Sofia',
    lastName: 'Recherche',
    email: 'novahaus.demo.cold@example.com',
    phone: '+49 151 10000003',
    wohnung: 'beide',
    wohnungLabel: 'Beide Wohnungen',
    zeitrahmen: 'informieren',
    zeitrahmenLabel: 'Informiert sich erst',
    eigenkapital: 'keine-angabe',
    eigenkapitalLabel: 'Keine Angabe',
    finanzierung: 'benoetigt-hilfe',
    finanzierungLabel: 'Braucht Unterstuetzung',
    score: 46,
    nextAction: 'Nurture-Mail senden und spaeter erneut nachfassen.',
    emailSubject: 'Weitere Informationen zu Ihrer Immobiliensuche',
    emailDraft:
      'Hallo Sofia,\n\nvielen Dank fuer Ihre Anfrage. Wir senden Ihnen gern weitere Informationen und halten Sie zu passenden Angeboten auf dem Laufenden.\n\nFalls Ihr Kaufzeitraum konkreter wird oder Sie Ihre Finanzierung klaeren moechten, antworten Sie einfach kurz auf diese E-Mail.\n\nViele Gruesse\nNovaHaus Immobilien',
  },
  not_qualified: {
    key: 'not_qualified',
    label: 'Not Qualified',
    status: 'not_qualified',
    priority: 'P4',
    segment: 'not_qualified',
    badge: 'Budget wird weich ausgesiebt',
    firstName: 'Lukas',
    lastName: 'Budgetcheck',
    email: 'novahaus.demo.budget@example.com',
    phone: '+49 151 10000004',
    wohnung: '3-zimmer',
    wohnungLabel: '3-Zimmer mit Garten',
    zeitrahmen: 'sofort',
    zeitrahmenLabel: 'So schnell wie moeglich',
    eigenkapital: 'unter-30k',
    eigenkapitalLabel: 'Unter 30.000 EUR',
    finanzierung: 'benoetigt-hilfe',
    finanzierungLabel: 'Braucht Unterstuetzung',
    score: 18,
    nextAction: 'Keine direkte Callcenter-Uebergabe; alternative Finanzierungshinweise senden.',
    emailSubject: 'Ihre Anfrage bei NovaHaus Immobilien',
    emailDraft:
      'Hallo Lukas,\n\nvielen Dank fuer Ihr Interesse. Fuer dieses Angebot empfehlen wir in der Regel mehr Eigenkapital, damit die Finanzierung realistisch geprueft werden kann.\n\nWir koennen Ihnen aber gern alternative Optionen oder Hinweise zur Finanzierungsvorbereitung senden.\n\nViele Gruesse\nNovaHaus Immobilien',
  },
}

export const DEMO_SCENARIO_ORDER = ['hot', 'warm', 'cold', 'not_qualified']

export function getDemoScenario(key) {
  return DEMO_SCENARIOS[key] || DEMO_SCENARIOS.hot
}
